# Generated by Django 2.2.3 on 2019-07-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contanct_date',
            new_name='contact_date',
        ),
    ]
